config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render 'new'
    end
  end

  def destroy
    @flat = Flat.find(param[:id])
    @flat.delete
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats (<%= @flats.count %>)</h1>
    </div>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4">
        <div class="card">
          <h3><%= flat.name %></h3>
          <p><%= flat.description.truncate(100, separator: ' ') %></p>
          <div class="flex">
            <div class="flex">Max Guests: <%= flat.number_of_guests %></div>
            <div class="flex">Price per Night: € <%= flat.price_per_night %></div>
          </div>
          <div class="btn"> <%= link_to 'More Info', flat_path(flat) %></div>
          <div class="btn"> <%= link_to 'Delete', flat_path(flat), method: :delete, data: {confirm: "Are you sure?"} %> </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a new Flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="header">
    <h1> <%= @flat.name %> </h1>
    <p> <%= @flat.address %> </p>
  </div>
  <div class="info">
    <h2>A bit more about this flat</h2>
    <p> <%= @flat.description %> </p>
  </div>
  <div class="details">
    <h2>Details</h2>
    <div class="flex">
      <div class="flex">Max Guests: <%= @flat.number_of_guests %></div>
      <div class="flex">Price per Night: € <%= @flat.price_per_night %></div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <span class="navbar-brand mb-0 h1">Simple Airbnb</span>
      <%= link_to 'Add Flat', new_flat_path, class: "btn btn-primary" %>
    </nav>
    <%= yield %>
  </body>
</html>